version: '3.8'

services:
  web:
    build: .
    container_name: virtual_app
    restart: always
    ports:
      - "5000:5000" # Puerto 5000 para dejar el 80 libre a Nginx
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - SECRET_KEY=${SECRET_KEY}
      - PASSWORD_ADMIN=${PASSWORD_ADMIN}
      - VERIFY_TOKEN=${VERIFY_TOKEN}
      - WHATSAPP_SECRET=${WHATSAPP_SECRET} # <--- AGREGADO: Vital para seguridad de Webhook
      - TZ=${TZ}
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: virtual_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - db_data:/var/lib/mysql
    command: --default-time-zone='-06:00'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: virtual_pma
    restart: always
    links:
      - db
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: ${TZ}

volumes:
  db_data:

